### ISSUE TITLE
Possibly leaking a handler registration in operator=

### ISSUE THREAD

**Issue by victork1996** [ykfre/exceptions-stacktrace#4]
https://github.com/ykfre/exceptions-stacktrace/blame/master/exceptions-stacktrace/AutoExceptionStacktraceRegister.cpp#L69

Before taking ownership of the handler of `other`, you should check if `this` registered a handler and if so, remove it.

**Comment by ykfre** [comment]
This issue was fixed in https://github.com/ykfre/exceptions-stacktrace/commit/0621076fe0c1060ebe830034e622a2ca5960054d.
Thx for the report!
